version: "3"
services:
 mqtt:
      image: toke/mosquitto
      network_mode: bridge
      container_name: mqtt
      expose:
        - 1883
      ports:
        - 1883:1883
     #restart: unless-stopped
 sub:
      image: sub
      container_name: subscribe
      expose:
        - 1883
 pub:
      image: pub
      container_name: publisher
      expose:
        - 80
  