version: "3"
services:
#docker stop $(docker ps -a -q)
#A. docker run --name mqtt --restart=always --net=host -tid -v /volume1/docker/mqtt/config:/mqtt/config:ro -v /volume1/docker/mqtt/log:/mqtt/log -v /volume1/docker/mqtt/data/:/mqtt/data/ toke/mosquitto
#B. docker run --name mqtt --restart=unless-stopped --net=host -tid -v /volume1/docker/mqtt/config:/mqtt/config:ro -v /volume1/docker/mqtt/log:/mqtt/log -v /volume1/docker/mqtt/data/:/mqtt/data/ toke/mosquitto

#docker-compose up


 waterpomp:
      image: waterpomp
      privileged: true
      container_name: waterpomp
      restart: unless-stopped
 
 remtecontrol:
      image: remotecontrol
      container_name: remotecontrol
      restart: unless-stopped

 bridge:
      image: bridge
      container_name: bridge
      ports:
          - 80
      expose:
          - 80
      restart: unless-stopped
